# Generated by Django 5.2.6 on 2025-10-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_remove_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='apagado',
            field=models.BooleanField(default=False),
        ),
    ]
