# Generated by Django 5.2.6 on 2025-10-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_produto_apagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img',
            field=models.ImageField(blank=True, default='shopping.webp', null=True, upload_to='img'),
        ),
    ]
