# Generated by Django 5.2.6 on 2025-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_produto_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(upload_to='img'),
        ),
    ]
