# Generated by Django 5.2.6 on 2025-10-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_alter_produto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('ESCRITA', 'Escrita e Correção'), ('PAPEIS', 'Papéis e Cadernos'), ('ORG', 'Organização e Arquivamento'), ('ARTES', 'Artes e Criatividade'), ('ESCOLAR', 'Materiais Escolares e Escritório')], default=('ESCRITA', 'Escrita e Correção'), max_length=20),
            preserve_default=False,
        ),
    ]
