# Generated by Django 5.2.6 on 2025-10-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_dona'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.CharField(default='bic', max_length=255),
        ),
    ]
